"""add cancel, createdby, modifiedby, createdon, modifiedon columns

Revision ID: 2a3bf04f132c
Revises: 5f0797b632f4
Create Date: 2025-08-21 15:53:44.826913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a3bf04f132c'
down_revision: Union[str, Sequence[str], None] = '5f0797b632f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userroles', sa.Column('cancel', sa.String(), nullable=True))
    op.add_column('userroles', sa.Column('createdby', sa.String(), nullable=True))
    op.add_column('userroles', sa.Column('createdon', sa.DateTime(), nullable=True))
    op.add_column('userroles', sa.Column('modifiedby', sa.String(), nullable=True))
    op.add_column('userroles', sa.Column('modifieon', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('cancel', sa.String(), nullable=True))
    op.add_column('users', sa.Column('createdby', sa.String(), nullable=True))
    op.add_column('users', sa.Column('createdon', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('modifiedby', sa.String(), nullable=True))
    op.add_column('users', sa.Column('modifieon', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'modifieon')
    op.drop_column('users', 'modifiedby')
    op.drop_column('users', 'createdon')
    op.drop_column('users', 'createdby')
    op.drop_column('users', 'cancel')
    op.drop_column('userroles', 'modifieon')
    op.drop_column('userroles', 'modifiedby')
    op.drop_column('userroles', 'createdon')
    op.drop_column('userroles', 'createdby')
    op.drop_column('userroles', 'cancel')
    # ### end Alembic commands ###
