"""add hpassword column

Revision ID: 4385d79b0989
Revises: 9b93559f7d6b
Create Date: 2025-08-23 18:21:08.004062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlmodel import SQLModel

# revision identifiers, used by Alembic.
revision: str = '4385d79b0989'
down_revision: Union[str, Sequence[str], None] = '9b93559f7d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userroles_userrolesid'), table_name='userroles')
    op.drop_table('userroles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_usersid'), table_name='users')
    op.drop_table('users')
    #op.add_column('kusers', sa.Column('hpassword', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('kusers', 'firstname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('kusers', 'emailid',
               existing_type=sa.VARCHAR(),
               nullable=True),
    op.add_column('kusers', sa.Column('hpassword', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kusers', 'emailid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('kusers', 'firstname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('kusers', 'hpassword')
    op.create_table('users',
    sa.Column('usersid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('userrolesid', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('cancel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('createdby', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('createdon', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modifiedby', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('modifieon', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('usersid', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_usersid'), 'users', ['usersid'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('userroles',
    sa.Column('userrolesid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rolename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('cancel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('createdby', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('createdon', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modifiedby', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('modifieon', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('userrolesid', name=op.f('userroles_pkey'))
    )
    op.create_index(op.f('ix_userroles_userrolesid'), 'userroles', ['userrolesid'], unique=False)
    op.drop_column('kusers', 'hpassword')
    # ### end Alembic commands ###
