"""add cancel,createdby,createdon,modifiedby,modifiedon column

Revision ID: 9b93559f7d6b
Revises: 2a3bf04f132c
Create Date: 2025-08-22 15:30:30.904496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b93559f7d6b'
down_revision: Union[str, Sequence[str], None] = '2a3bf04f132c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kusers_username'), table_name='kusers')
    op.drop_table('kusers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kusers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('emailid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('userroleids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('kusers_pkey'))
    )
    op.create_index(op.f('ix_kusers_username'), 'kusers', ['username'], unique=False)
    # ### end Alembic commands ###
